### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by simurai** [mnquintana/atom-about#4]
Not sure about having the note about the metrics in the About page. It's a pretty controversial thing. :no_mouth: So it's good to be open about it, but then

> See the [atom/metrics](https://github.com/atom/metrics/) package for details and instructions to disable it.

feels a bit cheap. Why not add a checkbox right there? I know, it's the same as in the Welcome.

**Comment by mnquintana** [comment]
Yeah I agree that it should be easier to disable metrics, but like https://github.com/atom/welcome/pull/28 I think it's really blocked on https://github.com/atom/settings-view/issues/436.

I do want to keep the note about metrics though because one of the common complaints is that people feel Atom isn't open enough about it – right now the metrics notice is only shown on Welcome, which is a view people probably won't revisit after their first few times using Atom.

**Comment by simurai** [comment]
I see. Linking straight to the package's settings. Ya, that would be neat.

Ok, let's close it again.
